spring:
  application:
    name: egs
  datasource:
    url: jdbc:postgresql://localhost:5432/egs
    username: egs
    password: egs
  jpa:
    properties:
      hibernate:
        default_schema: egs
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: ${spring.jpa.properties.hibernate.default_schema}
    baseline-on-migrate: true
    locations:
      - "classpath:migrations"
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
